# Generated by Django 3.2 on 2021-09-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CNAB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('owner', models.CharField(max_length=14)),
                ('store', models.CharField(max_length=19)),
                ('transaction_type', models.CharField(choices=[('Débito', 'Debit'), ('Boleto', 'Bill'), ('Financiamento', 'Financing'), ('Crédito', 'Credit'), ('Recebimento Empréstimo', 'Receivement'), ('Vendas', 'Sales'), ('Recebimento TED', 'Ted'), ('Recebimento DOC', 'Doc'), ('Aluguel', 'Rent')], max_length=50)),
                ('transaction_signal', models.CharField(max_length=1)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=3, default=0.0, max_digits=9)),
                ('card', models.CharField(max_length=12)),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cnab',
                'ordering': ('-date', '-time'),
            },
        ),
    ]
