# Generated by Django 3.2 on 2021-09-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnab',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
