# Generated by Django 3.2 on 2021-09-18 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cnab', '0003_alter_cnab_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=19, unique=True)),
                ('cpf', models.CharField(max_length=14)),
                ('owner', models.CharField(max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'store',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='cnab',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='cnab',
            name='owner',
        ),
        migrations.AlterField(
            model_name='cnab',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cnabs', to='cnab.store', verbose_name='Loja'),
        ),
    ]
